#!/usr/bin/env bash

echo "*"
exit 0

## -----------

typeset -ug DEFIF

function getif(){
cat /proc/net/route|while read LINE; do
  oIFS=$IFS
  set -- $LINE
  if [ "$2"x = "00000000"x ]; then
    echo ${1:0:1}
        break
  fi
  IFS=$oIFS
done
}

DEFIF=$(getif)

if [ -z "${DEFIF}" ]; then
  echo '-'
else
  echo $DEFIF
fi
exit
