= handy-scripts

Handy scripts for bash shell el Co

== Bash

=== Shell environment

- `.bash_colors` -- source/include for `.bashrc` to enable enhanced coloring support
- `.bash_devel` -- source/include for `.bashrc` to enable project navigation and setup development environment

=== Projects competions

`.bash_devel` brings a new handy method to mavigate your projects in quick and efficient manner - `goproj` from everyvere.

The method expects you store your projects inside of `~/myProjects` folder and may navigate up to 3 levels down in it.
Dirs marked by leading underscore (i.e. `_skip_this_`) and projects not containing `.git` are skipped automatically.

=== Tools

- `password-gen` -- command-line tool to generate random passwords
- `findsym` -- command-line tool to search through all system shared libraries
for a specific symbol
- `slide-show` -- (recursive) slide show for JPEG/PNG collection using MPV

== Python

=== Python env

- `.pythonrc` -- include for python interactive mode to enable some useful hooks like auto-completion etc

== License

MIT LICENSE WITHOUT WARRANTY OF ANY KIND
